apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    app: cvat-db
  name: cvat-db
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  hostPath:
    path: "/tmp/cvat-db"
