apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    app: cvat-opa-claim0
  name: cvat-opa-claim0
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  hostPath:
    path: "/tmp/cvat-opa"
